/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned int otawa_cycles_t;

typedef otawa_cycles_t (*cycles_fun_t)($(proc)_inst_t *inst);



static otawa_cycles_t otawa_cycles_UNKNOWN($(proc)_inst_t *inst)
{
        /* this code should also be used as default value if
        an instruction has no otawa_cycles field */
        return 8;
}

$(foreach instructions)
static otawa_cycles_t otawa_cycles_$(IDENT)($(proc)_inst_t *inst) {
$(otawa_cycles)
};

$(end)


/* function table */
static cycles_fun_t $(proc)_cycles_table[] =
{
	otawa_cycles_UNKNOWN$(foreach instructions),
	otawa_cycles_$(IDENT)$(end)
};



/**
 * Get the OTAWA cycles of the instruction.
 * @return OTAWA cycles.
 */
otawa_cycles_t $(proc)_cycles($(proc)_inst_t *inst)
{
        return $(proc)_cycles_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
